"""add tipo to producao_insumos

Revision ID: 0267716c6c8f
Revises: fb1c2d3e4f5a
Create Date: 2026-06-19 16:33:24.586905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0267716c6c8f'
down_revision = 'fb1c2d3e4f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao_insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producao_insumos', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
