"""create movto table

Revision ID: 11898ad5f0af
Revises: 4365d6872e51
Create Date: 2026-06-22 13:56:19.356810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11898ad5f0af'
down_revision = '4365d6872e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('previsao_id', sa.Integer(), nullable=True),
    sa.Column('documento', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rubrica_id', sa.Integer(), nullable=True),
    sa.Column('historico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['previsao_id'], ['previsao.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recurso.id'], ),
    sa.ForeignKeyConstraint(['rubrica_id'], ['rubrica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movto')
    # ### end Alembic commands ###
