"""add data_renovacao to quotes

Revision ID: 1f183ca1067f
Revises: 3c35784ad38b
Create Date: 2026-06-20 09:43:14.800464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f183ca1067f'
down_revision = '3c35784ad38b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_renovacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('data_renovacao')

    # ### end Alembic commands ###
