"""create recurso table

Revision ID: 4365d6872e51
Revises: b4ed2c94429c
Create Date: 2026-06-22 12:15:08.077316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365d6872e51'
down_revision = 'b4ed2c94429c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Integer(), server_default='0', nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurso')
    # ### end Alembic commands ###
