"""add responsavel to compra_eventos

Revision ID: 43f2fee87f18
Revises: 964fd200ac0b
Create Date: 2026-07-17 10:35:04.239131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f2fee87f18'
down_revision = '964fd200ac0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compra_eventos', schema=None) as batch_op:
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###
