"""add client relationship to quote

Revision ID: 44ba1d73b41e
Revises: a57549c56a0c
Create Date: 2026-06-12 15:33:00.747539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ba1d73b41e'
down_revision = 'a57549c56a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
