"""add evento_tema to orders

Revision ID: 74207fa1b00f
Revises: cf5f9df19ca8
Create Date: 2026-06-12 14:45:54.360660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74207fa1b00f'
down_revision = 'cf5f9df19ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evento_tema', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('evento_tema')

    # ### end Alembic commands ###
