"""add_compra_status_dates

Revision ID: 80ea70cd176a
Revises: b3c4d5e6f7a8
Create Date: 2026-07-17 09:14:19.127496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ea70cd176a'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autorizacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('aquisicao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cancelado', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('devolucao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('devolucao')
        batch_op.drop_column('cancelado')
        batch_op.drop_column('aquisicao')
        batch_op.drop_column('autorizacao')

    # ### end Alembic commands ###
