"""add_compra_eventos_remove_date_cols

Revision ID: 964fd200ac0b
Revises: 80ea70cd176a
Create Date: 2026-07-17 10:11:23.293078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964fd200ac0b'
down_revision = '80ea70cd176a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compra_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('aquisicao')
        batch_op.drop_column('devolucao')
        batch_op.drop_column('data_recepcao')
        batch_op.drop_column('autorizacao')
        batch_op.drop_column('cancelado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelado', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('autorizacao', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_recepcao', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('devolucao', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aquisicao', sa.DATE(), autoincrement=False, nullable=True))

    op.drop_table('compra_eventos')
    # ### end Alembic commands ###
