"""add cpf cnpj insc_estadual to conta

Revision ID: c7ae46145cc7
Revises: 77769f39bb34
Create Date: 2026-06-16 17:55:35.532262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ae46145cc7'
down_revision = '77769f39bb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('insc_estadual', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('insc_estadual')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
