"""make forma_pagamento_id nullable in orders and quotes

Revision ID: efe49ca52245
Revises: 7f0e2b8c1a3d
Create Date: 2026-06-28 07:08:12.072128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe49ca52245'
down_revision = '7f0e2b8c1a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('forma_pagamento_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
