"""add variacao to previsoes

Revision ID: f3a4c73bd1d9
Revises: b33b9ad40221
Create Date: 2026-06-22 09:24:01.068186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a4c73bd1d9'
down_revision = 'b33b9ad40221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('previsoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variacao', sa.Numeric(precision=12, scale=2), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('previsoes', schema=None) as batch_op:
        batch_op.drop_column('variacao')

    # ### end Alembic commands ###
